package com.versacomllc.training.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Entity for customer data.
 * 
 * @author Shamim Ahmmed
 * 
 */
@Entity
@Table(name = "user")
public class Employee extends AbstractEntity {

	/** Employee ID generated by us. */
	@Column(name = "employee_id", length = 100)
	private String employeeId;

	/** Employee email. */
	@Column(name = "email", length = 255)
	private String email;

	@Column(length = 255)
	private String salt;

	@Column(name = "hashed_password", length = 255)
	private String hashedPassword;

	/** Employee name. */
	@Column(name = "first_name", length = 255)
	private String firstName;

	/** Employee name. */
	@Column(name = "last_name", length = 255)
	private String lastName;

	/** Employee phone. */
	@Column(name = "phone", length = 255)
	private String phone;
	
	/** Employee phone. */
	@Column(name = "address", length = 255)
	private String address;
	
	/** Employee role. */
	@Column(name = "role", length = 100)
	private String role;

	public String getEmployeeId() {
		return employeeId;
	}

	public void setEmployeeId(String employeeId) {
		this.employeeId = employeeId;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
	public String getRole() {
		return role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public String getSalt() {
		return salt;
	}

	public void setSalt(String salt) {
		this.salt = salt;
	}

	public String getHashedPassword() {
		return hashedPassword;
	}

	public void setHashedPassword(String hashedPassword) {
		this.hashedPassword = hashedPassword;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

}
